---
- name: Get minikube installed version
  ansible.builtin.command: "minikube version --short"
  register: minikube_info
  changed_when: false
  failed_when: false

- name: Check if minikube is already installed with the correct version
  ansible.builtin.set_fact:
    minikube_already_installed: "{{ minikube_info is defined and minikube_info.stdout == minikube_version }}"

- name: Install minikube
  ansible.builtin.include_tasks: "install-minikube.yml"
  when: not minikube_already_installed
