---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    minikube_version: "v1.35.0"
    should_verify_minikube_checksum: true

  tasks:
    - name: Include willbrid.minikube_installer
      ansible.builtin.include_role:
        name: "willbrid.minikube_installer"
