---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    minikube_bin_dir: "/usr/local/bin"
    minikube_version: "v1.35.0"

  tasks:
    - name: Get minikube binary version
      ansible.builtin.command: "{{ minikube_bin_dir }}/minikube version --short"
      register: minikube_info
      changed_when: false
    - name: Check minikube correct version
      ansible.builtin.assert:
        that:
          - minikube_info.stdout == minikube_version
        fail_msg: "incorrect version of minikube"
